### ISSUE TITLE
System.NotSupportedException when an FFmpeg DLL needs a dependency

### ISSUE THREAD

**Issue by CraigN** [Ruslan-B/FFmpeg.AutoGen.Questions#41]
We custom build our FFmpeg library using vcpkg. What we noticed was that for certain builds we were getting a `System.NotSupportedException` for all avcodec DLL related methods.

In this specific case we were building the openh264, x264 and x265 library support using a command line along the lines of:

```powershell
.\bootstrap-vcpkg.bat
.\vcpkg install ffmpeg[avcodec,avdevice,avfilter,avformat,swresample,swscale,openh264,x264,x265]:x64-windows-release
```

This produces the usual FFmpeg 6.1 DLLs in the `installed\x64-windows-release\bin` directory along with `libx264-164.dll` and `libx265.dll` and `openh264-6.dll` files.

When using the FFmpeg.AutoGen package, we set the `ffmpeg.RootPath` to the output bin directory e.g. `D:\Projects\vcpkg\installed\x64-windows-release\bin`.

However, unless we put the FFmpeg output folder in the path (e.g. use the Kernel32 SetDllDirectory method) then we get `System.NotSupportedException` every time we make a call against the avcodec library (e.g. `ffmpeg.avcodec_license`).

Is there a simpler way to solve this inside the FFmpeg.AutoGen package?

**Comment by Ruslan-B** [comment]
Your inquiry presents a challenge due to the lack of comprehensive context and specifics. If the example project from the repository functions correctly, it raises questions about the nature of the issues you're encountering. It's crucial to understand that troubleshooting such complex scenarios requires detailed information, including potential error messages or stack traces.

Please ensure that the binaries you're using export the necessary functions. The presence of other packages and abstraction layers in your setup suggests that a closer examination of these elements may reveal the root of the problem. Understanding how interoperation (interop) works is fundamental in these cases, and it's apparent that a significant portion of difficulties arise from a lack of clarity in this area.

This project is designed for use by those with a solid grasp of its mechanics, not necessarily to provide education on its operation. While it may seem blunt, the intention is not to offend but to highlight the importance of a deep, working knowledge of the technology and its application.

Your approach to seeking help should be more focused and detailed. Offering a clear description of what exactly is not working and why, accompanied by relevant errors or stack traces, will significantly increase the chances of receiving effective assistance. It's essential to engage with this matter seriously and invest the necessary time to understand the underlying principles and mechanics.

Let's approach this with a mindset geared towards constructive problem-solving, ensuring we provide all the necessary details to facilitate accurate and helpful responses.

**Comment by Ruslan-B** [comment]
#closed

**Comment by Ruslan-B** [comment]
google is you friend you have learn interop and c export

**Comment by Ruslan-B** [comment]
otherwise explain yourself in a straight manner why we should solve something witch is working for over hundred 100 consumer projects  only on GitHub

**Comment by Ruslan-B** [comment]
Didn't noticed it is questions, apology right place - hens still vague

**Comment by Ruslan-B** [comment]
In dotnet 6 you have NativeLibrary which works well - try FFmpeg.AutoGen.Bindings.DynamicallyLinked

**Comment by Ruslan-B** [comment]
binaries you use most probably have no C exports

**Comment by CraigN** [comment]
I think you're misunderstanding the issue. I completely understand that many projects are using FFmpeg.AutoGen successfully using precompiled versions of the FFmpeg binaries.

The version of FFmpeg libraries that I am compiling with vcpkg all have the correct exports in their metadata. I've verified it with DUMPBIN.

However the problem is that when the DLL is loaded, the DLL itself can't find its dependencies which results in what appears to be an error in FFmpeg.AutoGen P/Invoking the method on for example avcodec.

In terms of setting the DLL search path for the process it's simple to just use the Vanara.PInvoke.Kernel32 package and call SetDllDirectory.

So my post here was more a question about how it should be done from an FFmpeg.AutoGen package point of view and perhaps to provide something that other users might find if they come across a similar issue.

**Comment by Ruslan-B** [comment]
Which nuget packages (name and version) are you using? Normally you don't need to use SetDllDirectory and just use DynamicallyLoadedBindings.LibrariesPath and after call DynamicallyLoadedBindings.Initialize()

**Comment by Ruslan-B** [comment]
On incase FFmpeg.AutoGen.Bindings.DynamicallyLinked you have to implement Assebly Resolver from .net6+ you also need to call DynamicallyLinked.Initialize() it updates vectors table in Abstraction layer.

There are also none abstract version here you just need to set ffmpeg.RootPath = ...
And it supposed to be sufficient .
NotSupportedException might be indication of missing Initialize call

Given you might have other libraries which a dependency, might be good idea to preload them - loaders are available via any implementation inherited from FunctionResolverBase.
