### ISSUE TITLE
avformat_open_input return error: -1414092869

### ISSUE THREAD

**Issue by nowayout** [Ruslan-B/FFmpeg.AutoGen.Questions#6]
version 4.2.2
The code print error: avformat_open_input: -1414092869, can't show device info.
`public unsafe void show_dshow_device()`
`{`
`            AVFormatContext* ictx = ffmpeg.avformat_alloc_context();`
`            AVDictionary* options = null;`
`            ffmpeg.av_dict_set(&options, "list_devices", "true", 0);`
`            AVInputFormat* fmt = ffmpeg.av_find_input_format("dshow");`
`            Console.WriteLine("==========Device Info==========");`
`            int ret = ffmpeg.avformat_open_input(&ictx, "video=dummy", fmt, &options);`
`            if(ret != 0)`
`            {`
`                Console.WriteLine("avformat_open_input: {0}", ret);`
`            }`
`            Console.WriteLine("===============================");`
`       }`

But the C code is correct, can show device info.
`void show_dshow_device(){`
`	AVFormatContext *pFmtCtx = avformat_alloc_context();`
`	AVDictionary* options = NULL;`
`	av_dict_set(&options, "list_devices", "true", 0);`
`	AVInputFormat *iformat = av_find_input_format("dshow");`
`	printf("Device Info=============\n");`
`	avformat_open_input(&pFmtCtx, "video=dummy", iformat, &options);`
`	printf("========================\n");`
`}`

**Comment by nowayout** [comment]
> It is not binding related, I tried to run your sample `ffmpeg.av_find_input_format("dshow")` gives 0x0000000000000000. Most-probably means this format is not supported with my version of FFmpeg binaries. In my case avformat_open_input gives -2.

But the C code is correct, can show device info.
`void show_dshow_device(){`
`AVFormatContext *pFmtCtx = avformat_alloc_context();`
`AVDictionary* options = NULL;`
`av_dict_set(&options, "list_devices", "true", 0);`
`AVInputFormat *iformat = av_find_input_format("dshow");`
`printf("Device Info=============\n");`
`avformat_open_input(&pFmtCtx, "video=dummy", iformat, &options);`
`printf("========================\n");`
`}`

**Comment by Ruslan-B** [comment]
Few thing to clarify.
You read the issue template, right?
You posted issue anyway conscientiously breaking rules.
You didn't read thoroughly my answer as I indicated that in my case even ```av_find_input_format``` giving ```null ``` in replay. Usually means you are using custom build of FFmpeg.

My point of view, ```avformat_open_input``` is most commonly used function and my project has over 100+ usages in other projects.

I can conclude problem lies in your environment.
Thus, you the only one who can solve it - you, I only can give some hints:
- enable FFmpeg logging like in example project;
- use ```av_strerror``` to get descriptive message;
- stop repeating mantras ```But the C code is correct``` and check that you are using same binaries? Besides did you even try to compile C code? As C version has no check and no printf. 
- don't post issues like this, otherwise you will get a permanent ban.

**Comment by nowayout** [comment]
Yes, you're right. I found the reason. I set the log level as this:
ffmpeg.av_log_set_level(ffmpeg.AV_LOG_ERROR);
It will not show device info.

Now I change it:
ffmpeg.av_log_set_level(ffmpeg.AV_LOG_VERBOSE);
All things OK.

Thanks.
